version: "3.8"
services:
  postgres:
    container_name: postgres
    ports:
      - 5432:5432
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: api_backend
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
